### ISSUE TITLE
Bug thread multipage

### ISSUE THREAD

**Issue by Fafi06** [StudioAgate/EsterenForum#1]
Sur les articles multi-pages, cliquer sur l'artcile mène à la 1ère page au lieu de la dernière page.
Du coup on se retrouve à lire des sujets de 2010... et encore avant de s'appercevoir d'un truc

Bizarrement, il n'affiche pas que l thread est multi-pages non plus. M'a fallu trouver sur la première page le raccourci "dernier message non lu" pour arriver au bon endroit

**Comment by Pierstoval** [comment]
Je suis en train de réinstaller le projet en local pour debug tout ça 😃

**Comment by Pierstoval** [comment]
C'est corrigé ! Merci 😄
